# Site settings
title: Jose Rosello
email: work@rosello.me
url: http://www.rosello.me
description: "Personal website of Jose Rosello, New York-based software developer"
skills: "Software Developer"
meta_author: Rosello Jose

# Google webmaster tools
google_verify: u1SJaxWE0dXBKhL3rVOCEFYIAb1bZUBDXWCUEzoiuhQ

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BA4C63 #18bc9c #80B3FF
  primary-rgb: "186,76,99" #"24,288,156" #"128,179,255"
  primary-dark: A1334A
  secondary: 262322 #2c3e50 #FD6E8A
  secondary-dark: 000000 #233140 #A2122F

# Footer settings
footer:
  copyright: Jose Rosello
  location: Contact
  social: Elsewhere
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jrosello0
  - title: github
    url: http://github.com/jmr0

# Postal address (add as many lines as necessary)
address:
  - line: ""

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
